### ISSUE TITLE
Parse error for package.json on Windows.

### ISSUE THREAD

**Issue by TheFacto** [cerner/one-cerner-style-icons#6]
## Overview
* When attempting to install this repo on Window 10 an error occurs.

```bash
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! file C:\Users\wr020200\AppData\Local\Temp\npm-4584-e21d83b1\git-cache-e3ad128e\f88de1caabc99c621e67192ec1f3749389823744\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No value found for key version at 3:14
npm ERR!   "version": “1.2.1”
```

## Investigation
* Looks like there's a strange quotation character for the package.json version
![image](https://cloud.githubusercontent.com/assets/1235049/26833045/e88dfec0-4a96-11e7-8953-c8121dda4ba7.png)

**Comment by Slothjams** [comment]
I've updated the package.json. Should work now
