### ISSUE TITLE
archive this project

### ISSUE THREAD

**Issue by sambao21** [cerner/one-cerner-style-icons#64]
Is this project active? Can we archive this project? By archiving, previously release assets will be untouched, but support will cease for this project going forward. If anyone has any reasons this project should not be archived, please comment by March 1st.

**Comment by jeremyfuksa** [comment]
This project is a dependency of `terra-core` and needs to be moved wherever Terra is going.

**Comment by sambao21** [comment]
Thanks for response. We can bundle this with Terra's plans then and archive on it's schedule.
